default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: bdd_development
  username: polluser
  password: simplonco
  host: localhost

test:
    adapter: postgresql
    database: bdd_test
    username: polluser
    password: simplonco
    host: localhost

production:
    adapter: postgresql
    database: bdd_prod
    username: polluser
    password: ENV['DB_PASSWORD']
    host: localhost
